### ISSUE TITLE
Consistency level hardcoding is a big issue

### ISSUE THREAD

**Issue by ascaler** [ralphtheninja/documentdb-client#3]
In some cases when database needs to be configured with mongo compatibility and global deployment then ConsistencyLevel.Session is required and ConsistencyLevel.Strong doesn't work. It should be either configurable or could be defined on need basis.

**Comment by ralphtheninja** [comment]
@ascaler Absolutely. Mind you, I created this module for my own use case and I don't mind updating this! :)

**Comment by ralphtheninja** [comment]
Feel free to make a PR if you're up for it.

**Comment by ralphtheninja** [comment]
https://github.com/ralphtheninja/documentdb-client/commit/1b228719e99c1f270983ea9acb3d226ff746f3d3

**Comment by ralphtheninja** [comment]
4.1.1

**Comment by ascaler** [comment]
Thank you Ralph. We are just trying to help the project and we can help to improve it. We will be promoting the project as we like it very much and very useful.
